### ISSUE TITLE
Multiple certificates ?

### ISSUE THREAD

**Issue by esprit-libre** [systemli/ansible-role-letsencrypt#25]
Hello,

I look for a role that uses `webroot` mode, and this one seams good!
But reading quickly the code, I guess it only manage one certificate (eventually with multiple domains).

Is there something I miss to manage multiple certificates?
Best regards

**Comment by t2d** [comment]
you can also call it per virtual host like this:
```
- name: request Let's Encrypt certificate for vhost
  include_role:
    name: systemli.letsencrypt
  vars:
    letsencrypt_setup: false
    letsencrypt_cert:
      name: "{{ item.host }}"
      domains: "{{ item.domains }}"
...
```
