### ISSUE TITLE
How to include this role?

### ISSUE THREAD

**Issue by strarsis** [systemli/ansible-role-letsencrypt#31]
```yml
- hosts: web
  become: yes

  tasks:
    - name: Include letsencrypt_cert
      include_role:
        name: letsencrypt_cert
      vars:
        letsencrypt_account_email: info@example.com
        letsencrypt_cert:
          name: staging.example.com
          domains:
            - staging.example.com
          challenge: http
          http_auth: apache
          opts_extra: '--server https://localca/acme/acme/directory'
          services:
            - apache2
````

The task name is logged during the run - but nothing else happens and no certificate is signed.
