### ISSUE TITLE
How to install certbot (and dependencies) when all variables set

### ISSUE THREAD

**Issue by MrAlci** [systemli/ansible-role-letsencrypt#5]
ansible-role-letsencrypt/tasks/main.yml
---

- include: install.yml
  when: not letsencrypt_cert|d()

- include: certificate.yml
  when: letsencrypt_cert|d()

How is this supposed to work? Do we need a seperate setup phase or what is best practice to make it work? 

We tried to setup with the role, but if we preconfigure all variables, the install does not run (which makes sense with the above code). But how can we install it then when we have a new server and with following the role logic and following the best practices.

**Comment by xshadow** [comment]
MrAlci, you don't have to do that. 

The logic is that you call the letsencrypt role from the role, with which you setup the website: 

```
- name: request Let's Encrypt certificate for vhost
  include_role:
    name: letsencrypt
  vars:
    - letsencrypt_cert:
        name: "{{ vhost_item.host }}"
        domains: "{{ letsencrypt_domains }}"
        challenge: "{{ vhost_item.ssl.challenge|default('http') }}"
        webroot_path: "{{ apache_vhosts_docroot_tmp|d(apache_vhosts_docroot) }}"
        services: "{{ [ 'apache2' ] + vhost_item.ssl.letsencrypt_services_extra|default([]) }}"
  when: letsencrypt_domains|d()
```

**Comment by doobry-systemli** [comment]
@MrAlci: imagine a setup with hundreds of certificates. If we would rund theLE installation tasks each time a certificate is obtained, that would be a huge performance killer.

**Comment by NorbertRonecker** [comment]
Maybe it's possible to create a single playbook with 2step phases...
for example:
```
---
- hosts: setuple
  become: yes
  roles:
    - letsencrypt

- hosts: frontend:
  become: yes
  roles:
    - letsencrypt
  vars:
    - letsencrypt_cert:
        name: "{{ vhost_item.host }}"
        domains: "{{ letsencrypt_domains }}"
        challenge: "{{ vhost_item.ssl.challenge|default('http') }}"
        webroot_path: "{{ apache_vhosts_docroot_tmp|d(apache_vhosts_docroot) }}"
        services: "{{ [ 'apache2' ] + vhost_item.ssl.letsencrypt_services_extra|default([]) }}"
...
```

While this is possible... it's garbage... but possible. but also garbage...

**Comment by patsevanton** [comment]
Fixed by this playbook
```
- hosts: letsencrypt
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
    - name: install python3-certbot-apache
      apt: name=python3-certbot-apache state=present
  roles:
    - role: geerlingguy.apache
    - role: systemli.letsencrypt
```
