### ISSUE TITLE
Could not choose appropriate plugin: The requested apache plugin does not appear to be installed

### ISSUE THREAD

**Issue by patsevanton** [systemli/ansible-role-letsencrypt#57]
Hello! Thanks for role letsencrypt
I try install 
#### Playbook
```
- hosts: letsencrypt
  become: true
  roles:
    - role: geerlingguy.apache
    - role: systemli.letsencrypt
```
#### Inventory
```
all:
  children:
    letsencrypt:
      hosts:
        "letsencrypt":
          ansible_host: "xxxx"
  vars:
    apache_vhosts:
      - servername: "letsencrypt.xxx.sslip.io"
        documentroot: "/var/www/html"
    letsencrypt_opts_extra: "--register-unsafely-without-email"
    letsencrypt_cert:
      name: letsencrypt.xxx.sslip.io
      domains:
        - letsencrypt.xxx.sslip.io
      challenge: http
      http_auth: apache
      services:
        - apache2
```

#### Output
```
TASK [systemli.letsencrypt : register Let's Encrypt certificate with HTTP challenge] ***************************************************************************************************
Tuesday 26 April 2022  12:07:16 +0600 (0:00:00.024)       0:01:19.398 *********
fatal: [letsencrypt]: FAILED! => changed=true
  cmd:
  - certbot
  - certonly
  - --apache
  - --cert-name
  - letsencrypt.51.250.21.141.sslip.io
  - --register-unsafely-without-email
  - --domains
  - letsencrypt.51.250.21.141.sslip.io
  - --keep-until-expiring
  - --expand
  - --allow-subset-of-names
  - --non-interactive
  - --agree-tos
  - --post-hook
  - systemctl restart apache2
  delta: '0:00:00.306110'
  end: '2022-04-26 06:07:20.466023'
  msg: non-zero return code
  rc: 1
  start: '2022-04-26 06:07:20.159913'
  stderr: |-
    Saving debug log to /var/log/letsencrypt/letsencrypt.log
    Could not choose appropriate plugin: The requested apache plugin does not appear to be installed
    The requested apache plugin does not appear to be installed
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

**Comment by patsevanton** [comment]
Fixed by this playbook
```
- hosts: letsencrypt
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
    - name: install python3-certbot-apache
      apt: name=python3-certbot-apache state=present
  roles:
    - role: geerlingguy.apache
    - role: systemli.letsencrypt
```
