### ISSUE TITLE
Nginx TLS config is not applied to virtual host

### ISSUE THREAD

**Issue by zolia** [systemli/ansible-role-letsencrypt#82]
Hello, 

Trying to use this role on Debian 12
Using as: 

```
---
- name: Setup reverse proxy
  hosts: [monitoring]
  vars_files:
    - vars/main.yml
  vars:
    letsencrypt_account_email: "myemail@gmail.com"
  roles:
    - jdauphant.nginx
    - systemli.letsencrypt

# vars/main.yml
nginx_sites:
  default:
    - listen 80
    - server_name mydomain.com
    - location / { proxy_pass http://localhost:8000; }

letsencrypt_account_email: "myemail@gmail.com"
letsencrypt_cert:
  name: mydomain.com
  challenge: http
  http_auth: nginx
  letsencrypt_account_email: "myemail@gmail.com"
  domains:
    - mydomain.com

```

I would expect TLS config to be applied, but it runs like: 

```
- name: Register Let's Encrypt certificate with HTTP challenge
  ansible.builtin.command: >
    certbot certonly
    ...
```

I would expect it to be: 

```
- name: Register Let's Encrypt certificate with HTTP challenge
  ansible.builtin.command: >
    certbot run
    ...
```

Otherwise virtual host TLS configuration is not applied. Only certificate is fetched. 
Runninng cerbot manually fixes the issue:

`certbot run --nginx -n --domains mydomain.com`
