### ISSUE TITLE
Nginx registration failing because certificate doesn't exist

### ISSUE THREAD

**Issue by asfarley** [systemli/ansible-role-letsencrypt#98]
I was using this role successfully previously, but I noticed certbot wasn't auto-renewing and it appears to be happening because I'm using nginx. 

I've switched http_auth from standalone to nginx.

~~It looks like certbot doesn't like something because I'm seeing an error about missing command-line flags:~~

`Missing command line flags. For non-interactive execution, you will need to specify a plugin on the command line.  Run with '--help plugins' to see a list of options, and see https://eff.org/letsencrypt-plugins for more detail on what the plugins do and how to use them.`

(I resolved the previous issue by modifying my configuration from the values shown in the readme to the following:

```
- name: letsencrypt
  become: true
  remote_user: deploy
  hosts: all
  vars:
    letsencrypt_cert:
      name: '{{hostname}}'
      domains:
        - '{{hostname}}'
      challenge: http
    letsencrypt_http_auth: nginx
    letsencrypt_account_email: [my_email]
  roles:
    - role: systemli.letsencrypt
```

Note the change from having http_auth under letsencrypt_cert to letsencrypt_http_auth directly under vars. 

Now the previous error seems to be resolved, but I'm having a new problem: my passenger config file refers to the ssl certificates which would be generated by certbot. Thus, nginx throws an error:

`Error while running nginx -c /etc/nginx/nginx.conf -t.\n\n2025/04/30 23:37:25 [emerg] 202385#202385: cannot load certificate \"/etc/letsencrypt/live/[my_server]/fullchain.pem\"`

The error makes sense to me because it's true that this file doesn't exist yet, because the registration has not been completed. But how do I resolve this situation? If NGINX depends on the certbot cert, and registering the cert requires NGINX, isn't this a catch-22?
